from enums import ArcherEnums, BallistaEnums, CatapultEnums, FootmanEnums, HuntsmanEnums, KingEnums, KnightEnums, LancerEnums, NobleEnums, ScoutCavalryEnums, TrebuchetEnums, WagonerEnums, WarWagonEnums


archerDict = {ArcherEnums.NAME: 55,
                BallistaEnums.NAME: 85,
                CatapultEnums.NAME: 70,
                FootmanEnums.NAME: 65,
                HuntsmanEnums.NAME: 65,
                KingEnums.NAME: 100,
                KnightEnums.NAME: 55,
                LancerEnums.NAME: 15,
                NobleEnums.NAME: 15,
                ScoutCavalryEnums.NAME: 85,
                TrebuchetEnums.NAME: 85, 
                WagonerEnums.NAME: 75, 
                WarWagonEnums.NAME: 5}

ballistaDict = {ArcherEnums.NAME: 0,
                BallistaEnums.NAME: 0,
                CatapultEnums.NAME: 0,
                FootmanEnums.NAME: 0,
                HuntsmanEnums.NAME: 0,
                KingEnums.NAME: 0,
                KnightEnums.NAME: 0,
                LancerEnums.NAME: 0,
                NobleEnums.NAME: 0,
                ScoutCavalryEnums.NAME: 0,
                TrebuchetEnums.NAME: 0, 
                WagonerEnums.NAME: 0, 
                WarWagonEnums.NAME: 0}

catapultDict = {ArcherEnums.NAME: 85,
                BallistaEnums.NAME: 80,
                CatapultEnums.NAME: 75,
                FootmanEnums.NAME: 90,
                HuntsmanEnums.NAME: 75,
                KingEnums.NAME: 100,
                KnightEnums.NAME: 70,
                LancerEnums.NAME: 45,
                NobleEnums.NAME: 40,
                ScoutCavalryEnums.NAME: 80,
                TrebuchetEnums.NAME: 80, 
                WagonerEnums.NAME: 70, 
                WarWagonEnums.NAME: 15}

footmanDict = {ArcherEnums.NAME: 45,
                BallistaEnums.NAME: 25,
                CatapultEnums.NAME: 15,
                FootmanEnums.NAME: 55,
                HuntsmanEnums.NAME: 5,
                KingEnums.NAME: 100,
                KnightEnums.NAME: 1,
                LancerEnums.NAME: 1,
                NobleEnums.NAME: 1,
                ScoutCavalryEnums.NAME: 12,
                TrebuchetEnums.NAME: 25, 
                WagonerEnums.NAME: 14, 
                WarWagonEnums.NAME: 1}
            
huntsmanDict = {ArcherEnums.NAME: 105,
                BallistaEnums.NAME: 55,
                CatapultEnums.NAME: 50,
                FootmanEnums.NAME: 105,
                HuntsmanEnums.NAME: 45,
                KingEnums.NAME: 100,
                KnightEnums.NAME: 25,
                LancerEnums.NAME: 10,
                NobleEnums.NAME: 5,
                ScoutCavalryEnums.NAME: 60,
                TrebuchetEnums.NAME: 55, 
                WagonerEnums.NAME: 50, 
                WarWagonEnums.NAME: 1}

kingDict = {ArcherEnums.NAME: 100,
                BallistaEnums.NAME: 100,
                CatapultEnums.NAME: 100,
                FootmanEnums.NAME: 100,
                HuntsmanEnums.NAME: 100,
                KingEnums.NAME: 100,
                KnightEnums.NAME: 100,
                LancerEnums.NAME: 100,
                NobleEnums.NAME: 100,
                ScoutCavalryEnums.NAME: 100,
                TrebuchetEnums.NAME: 100, 
                WagonerEnums.NAME: 100, 
                WarWagonEnums.NAME: 100}

knightDict = {ArcherEnums.NAME: 70,
                BallistaEnums.NAME: 85,
                CatapultEnums.NAME: 70,
                FootmanEnums.NAME: 75,
                HuntsmanEnums.NAME: 65,
                KingEnums.NAME: 100,
                KnightEnums.NAME: 55,
                LancerEnums.NAME: 15,
                NobleEnums.NAME: 15,
                ScoutCavalryEnums.NAME: 85,
                TrebuchetEnums.NAME: 85, 
                WagonerEnums.NAME: 75, 
                WarWagonEnums.NAME: 10}

lancerDict = {ArcherEnums.NAME: 95,
                BallistaEnums.NAME: 105,
                CatapultEnums.NAME: 105,
                FootmanEnums.NAME: 105,
                HuntsmanEnums.NAME: 105,
                KingEnums.NAME: 100,
                KnightEnums.NAME: 85,
                LancerEnums.NAME: 55,
                NobleEnums.NAME: 45,
                ScoutCavalryEnums.NAME: 105,
                TrebuchetEnums.NAME: 105, 
                WagonerEnums.NAME: 105, 
                WarWagonEnums.NAME: 25}

nobleDict = {ArcherEnums.NAME: 115,
                BallistaEnums.NAME: 125,
                CatapultEnums.NAME: 115,
                FootmanEnums.NAME: 125,
                HuntsmanEnums.NAME: 115,
                KingEnums.NAME: 100,
                KnightEnums.NAME: 105,
                LancerEnums.NAME: 75,
                NobleEnums.NAME: 55,
                ScoutCavalryEnums.NAME: 125,
                TrebuchetEnums.NAME: 125, 
                WagonerEnums.NAME: 125, 
                WarWagonEnums.NAME: 35}

scoutCavalaryDict = {ArcherEnums.NAME: 65,
                BallistaEnums.NAME: 28,
                CatapultEnums.NAME: 45,
                FootmanEnums.NAME: 70,
                HuntsmanEnums.NAME: 4,
                KingEnums.NAME: 100,
                KnightEnums.NAME: 6,
                LancerEnums.NAME: 1,
                NobleEnums.NAME: 1,
                ScoutCavalryEnums.NAME: 35,
                TrebuchetEnums.NAME: 55, 
                WagonerEnums.NAME: 45, 
                WarWagonEnums.NAME: 1}

trebuchetDict = {ArcherEnums.NAME: 85,
                BallistaEnums.NAME: 80,
                CatapultEnums.NAME: 75,
                FootmanEnums.NAME: 90,
                HuntsmanEnums.NAME: 75,
                KingEnums.NAME: 100,
                KnightEnums.NAME: 70,
                LancerEnums.NAME: 45,
                NobleEnums.NAME: 40,
                ScoutCavalryEnums.NAME: 80,
                TrebuchetEnums.NAME: 80, 
                WagonerEnums.NAME: 70, 
                WarWagonEnums.NAME: 15}

wagonerDict = {ArcherEnums.NAME: 0,
                BallistaEnums.NAME: 0,
                CatapultEnums.NAME: 0,
                FootmanEnums.NAME: 0,
                HuntsmanEnums.NAME: 0,
                KingEnums.NAME: 0,
                KnightEnums.NAME: 0,
                LancerEnums.NAME: 0,
                NobleEnums.NAME: 0,
                ScoutCavalryEnums.NAME: 0,
                TrebuchetEnums.NAME: 0, 
                WagonerEnums.NAME: 0, 
                WarWagonEnums.NAME: 0}

warWagonDict = {ArcherEnums.NAME: 125,
                BallistaEnums.NAME: 100,
                CatapultEnums.NAME: 195,
                FootmanEnums.NAME: 135,
                HuntsmanEnums.NAME: 195,
                KingEnums.NAME: 100,
                KnightEnums.NAME: 180,
                LancerEnums.NAME: 125,
                NobleEnums.NAME: 115,
                ScoutCavalryEnums.NAME: 195,
                TrebuchetEnums.NAME: 195, 
                WagonerEnums.NAME: 195, 
                WarWagonEnums.NAME: 65}

modifierDict = {ArcherEnums.NAME: archerDict,
                BallistaEnums.NAME: ballistaDict,
                CatapultEnums.NAME: catapultDict,
                FootmanEnums.NAME: footmanDict,
                HuntsmanEnums.NAME: huntsmanDict,
                KingEnums.NAME: kingDict,
                KnightEnums.NAME: knightDict,
                LancerEnums.NAME: lancerDict,
                NobleEnums.NAME: nobleDict,
                ScoutCavalryEnums.NAME: scoutCavalaryDict,
                TrebuchetEnums.NAME: trebuchetDict, 
                WagonerEnums.NAME: wagonerDict, 
                WarWagonEnums.NAME: warWagonDict}